sudo: false
before_install:
- mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20150712/texlive.tar.xz
  | tar -JxC $HOME/texlive
install:
- PATH=$HOME/texlive/bin/x86_64-linux:$PATH
- tlmgr install moderncv
- tlmgr install moderntimeline
script:
- make
deploy:
  provider: releases
  api_key:
    secure: Bly4GgbXT8c/9BGookNaLCG48EhH1rWpYwJzbJtPCGl6iTBe0FSm7EmpB9H03IAIc7skGQoRTsec/WgsbYU/o5Jl7sIrytOsritThe5rc1A3xUEo3tlts2DY1M2pYxIUDmQFtHFBzmvqmj+/1Th0tZj91uRBmC6Gr2tLZ1jXITdTZY4TpmfRgPd9aDsF1d8Kyzhltz3Kuu5dpyW/oi35yoXmqtFRcs0ue3X90xlH84Os4twJ09QBFjcCDme4jYC3VKxnKlULpQbVAhB3Lm5tG9iumAqkZRVCvaM++U4kyo39oehl+OGHgdNW665f2MZV+nQWu3y2PQsWWOvQNJnYcIXbSJtoiL8WreIwI1heKXdRTdnIaV53W2W35Gt/FwpXYm8F8b64SaAgtULcNq1+E8eN1MoElPo/5aPuW+yHZVNyynNS4uikHWZggwu/zbrm1oN6svB2dqMwdCl0bjgr79xxMnezzaOV9VrluhG0mFQXU347Wn/3YE+St+licGuihg9gVuQOyQSrlw3CRiGT7fHuPvvJe6RYLTJU+o5eVrP2Sp8tyrBwQiuT4ipmglqZ4C4weaJ2iywbXOlRTiQWJyoTXXBvgbX0+imjfLaUSxUfzd7UwmyI7xIT/qr/Z8hP7AqHlmhtLw1fwxXEK4T4lJk0cTW5eAi8URii48BFVZc=
  file: resume.pdf
  skip_cleanup: true
  on:
    branch: master
