sudo: false
before_install:
- mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20150712/texlive.tar.xz
  | tar -JxC $HOME/texlive
install:
- PATH=$HOME/texlive/bin/x86_64-linux:$PATH
- tlmgr install moderncv
- tlmgr install moderntimeline
script:
- make
deploy:
  provider: releases
  api_key:
    secure: bAKDJVHhyYOPc17H4NjAMeVrsjo7fukN8+olGEHoFtiaxbS3TOLxjD56cZBxyHKA7I3u3lsFZRWDeEBTuf8ZzADBgxTwILXeR8Nqu/MVXdcYXi4NRcpL0p0D6DRy+28BpwW8rBzbmZLPg3EZI804Rks09cIXJzqO1W3VzCLPr+OV99/2wb5k3tpRQwG5jy0e2dOOSPUBU9VS8fGQLKrW4V7DI1zpLVsK/pvaiX41iq5DqDGcMWnsY49fVP35UUWh7p2kh7U5BrPGamV3ozD7dD320KCBHm+1tVZWAZxdSLDBbKbifWGcBTlggRETqw9O3SjaO8ZHR6FRz83mvP5OZakhTtw2c03cPfVMoSRBon+h8Y5NIMf/uBRitYO2tqTbZVMH3B/81u1sXd4l7cw8ccmc6ILanMDKPfWRPepzFpRGZm2ZwfZ5k8deDdYJv7cIi/yOH1S+Kzc2r+5ChfkEskCW8604USUEWCFeWhEsx8gzqxgHnNw+FJgyH1ft5xOgyeyqOT3M278EXw9IaTMD34N74gFFGWg4E0NicfzT5XhkM1IfIrICRM9mj6pP9W7F8UA+vpVfkN03oA40bOWOe5Z2ND/mPSKAJ79GZEsaR81FIyf6DeQTLRH/H0dLy9D01ceKGHeKIHL2WW26+525s8djPErtMiDQ5mdCAtbF3t0=
  file: resume.pdf
  on:
    tags: true

